#
# Copyright(c) 2012-2013 ACCESS CO., LTD. All rights reserved.
#

# !BEGIN SECRET!
<%
  branch = (`git rev-parse --abbrev-ref HEAD` rescue '').chomp
  branch = ''           if branch == 'master'
  branch = '.' + branch if branch.size > 0
%>

sqlite_base: &sqlite_base
  adapter: sqlite3
  pool: 5
  timeout: 5000

local_default: &local_default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: postgres
  password: sanket

development:
  <<: *local_default
  database: cafe_dine_in_order_developement
  # jio_hotel_old_development

development_log:
  <<: *local_default
  database: db/cafe_dine_in_order_developement_log

test:
  <<: *local_default
  database: db/cafe_dine_in_order_test1

test_log:
  <<: *local_default
  database: db/cafe_dine_in_order_log

# !END SECRET!

postgres_base: &postgres_base
  adapter: postgresql
  username: sijioht01
  encoding: utf8
  port: 5432

production:
  <<: *postgres_base
  database: cafe_dine_in_order_pg
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1

production_log:
  <<: *postgres_base
  database: cafe_dine_in_order_pgLog
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1

